name: Assign Random Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Choose Random Reviewer
        run: |
          REVIEWERS=("ucey-star" "avalucianelson" "FlaIespa" "katyaivaniuk" "lewiskyron" "matviikotolyk" "Mykhailo-Chudyk" "nnnour")
          SELECTED_REVIEWER=${REVIEWERS[$RANDOM % ${#REVIEWERS[@]}]}
          echo "Selected reviewer: $SELECTED_REVIEWER"
          echo "reviewer=$SELECTED_REVIEWER" >> $GITHUB_ENV

      - name: Assign the Reviewer
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [process.env.reviewer]
            })
        env:
          reviewer: ${{ env.reviewer }}
